networks:
  app-net:
    driver: bridge

volumes:
  aggregator-db-volume:

services:
  # Service 1: Aggregator 
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    volumes:
      # Mount volume ke /app
      - aggregator-db-volume:/app
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8080/stats\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s 

  # Service 2: Publisher 
  publisher:
    build:
      context: .
      dockerfile: publisher.Dockerfile 
    depends_on:
      aggregator:
        condition: service_healthy 
    environment:
      - AGGREGATOR_URL=http://aggregator:8080
    networks:
      - app-net
